# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # New job to report build status
  report-build-status:
    # This job will only run after the build job completes successfully
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Report build status
        run: |
          echo "Reporting build status..."
          # Aquí puedes agregar comandos para reportar el estado de la build

  # New job to deploy the project
  deploy:
    # This job will only run after the report-build-status job completes successfully
    needs: report-build-status
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        run: |
          echo "Deploying to GitHub Pages..."
          # Aquí puedes agregar comandos para desplegar el proyecto
          # Por ejemplo, puedes usar `actions/deploy-pages` o hacer push a la rama gh-pages

